containerPlataform: rancher
replicaCount: 2

appName: "front-end"
namespace: "apps"
environment: "asgard"

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 1m
    memory: 64Mi

image:
  repository: "ewertonmarschalk/front-end"
  tag: 1.0.1
  pullPolicy: IfNotPresent
  ports:
    - name: http
      containerPort: 80
      protocol: TCP
      
service:
  type: ClusterIP
  port: 80
  targetPort: http
  portName: http
  protocol: TCP

ingress:
  enabled: true
  host: "frontend.cluster.local"
