{{- if and (eq .Values.ingress.enabled true) (eq .Values.containerPlataform "rancher") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        - pathType: ImplementationSpecific
          path: "/"
          backend:
            service:
              name: {{ .Values.appName }}
              port:
                name: http
{{- end }}